version: '3.9'

services:
  api:
    image: ghcr.io/root/gold-api:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  admin:
    image: ghcr.io/root/gold-admin:latest
    restart: always
    ports:
      - "8081:80"
      
  myapp:
    build: .
    ports:
      - "${APP_PORT}:80"
    env_file:
      - .env

