version: '3.8'

services:
  api:
    image: ghcr.io/your-username/gold-api:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  admin:
    image: ghcr.io/your-username/gold-admin:latest
    restart: always
    ports:
      - "8081:80"
