# بیلد برنامه فرانت‌اند
FROM node:18 AS build
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y \
    curl \
    git \
    docker.io \
    kubectl \
    python3-pip \
RUN npm install
RUN npm run build

# سرور Nginx برای سرو کردن
FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
