name: Deploy to Production

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production
      rollback_to:
        description: "Optional: rollback to specific tag (e.g. v1.0.0)"
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag version (normal or rollback)
        id: vars
        run: |
          if [[ -n "${{ github.event.inputs.rollback_to }}" ]]; then
            echo "tag=${{ github.event.inputs.rollback_to }}" >> $GITHUB_OUTPUT
            echo "rollback=true" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "rollback=false" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "rollback=false" >> $GITHUB_OUTPUT

      - name: Create deployment directory on server
        if: steps.vars.outputs.rollback != 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/gold-app-${{ steps.vars.outputs.tag }}

      - name: Transfer Docker Compose files
        if: steps.vars.outputs.rollback != 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml,.env"
          target: "~/gold-app-${{ steps.vars.outputs.tag }}"

      - name: Create .env file
        if: steps.vars.outputs.rollback != 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/gold-app-${{ steps.vars.outputs.tag }}
            cat > .env << EOL
            ASPNETCORE_ENVIRONMENT=${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'production' }}
            API_TAG=${{ steps.vars.outputs.tag }}
            ADMIN_TAG=${{ steps.vars.outputs.tag }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOL

      - name: Deploy to server
        if: steps.vars.outputs.rollback != 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/gold-app-${{ steps.vars.outputs.tag }}
            docker-compose pull
            # docker-compose run --rm gold-api dotnet ef database update
            docker-compose up -d
            rm -f ~/gold-app-current
            ln -s ~/gold-app-${{ steps.vars.outputs.tag }} ~/gold-app-current

      - name: Rollback to ${{ steps.vars.outputs.tag }}
        if: steps.vars.outputs.rollback == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/gold-app-${{ steps.vars.outputs.tag }}
            docker-compose up -d
            rm -f ~/gold-app-current
            ln -s ~/gold-app-${{ steps.vars.outputs.tag }} ~/gold-app-current

      - name: Clean old deployments
        if: steps.vars.outputs.rollback != 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~
            ls -dt gold-app-* | grep -v gold-app-current | tail -n +4 | xargs rm -rf
