name: CI/CD Backend/Admin

on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Copy source for API and Admin
      run: |
        # مسیر کپی سورس API
        mkdir -p ./deploy-src/api
        cp src/Gold.APIs/Gold.APIs.csproj ./deploy-src/api/
        cp -r src/Gold.Application ./deploy-src/api/Application
        cp -r src/Gold.Domain ./deploy-src/api/Domain
        cp -r src/Gold.Infrastructure ./deploy-src/api/Infrastructure
        cp -r src/Gold.SharedKernel ./deploy-src/api/SharedKernel

        # مسیر کپی سورس Admin
        mkdir -p ./deploy-src/admin
        cp src/Gold.Admin/Gold.Admin.csproj ./deploy-src/admin/
        cp -r src/Gold.Application ./deploy-src/admin/Application
        cp -r src/Gold.Domain ./deploy-src/admin/Domain
        cp -r src/Gold.Infrastructure ./deploy-src/admin/Infrastructure
        cp -r src/Gold.SharedKernel ./deploy-src/admin/SharedKernel


    - name: Install Liara CLI
      run: npm install -g @liara/cli@7
  
    - name: Deploy API to Liara
      env:
        LIARA_API_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
      run: |
        if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
          liara deploy --app back-api-shemsh --port 80 --path ./deploy-src/api/Gold.APIs.csproj --api-token="$LIARA_API_TOKEN" --no-app-logs --platform="dotnet" --debug
        elif [ "${{ github.ref }}" == "refs/heads/master" ]; then
          liara deploy --app pro-api-shemsh --port 80 --path ./deploy-src/api/Gold.APIs.csproj --api-token="$LIARA_API_TOKEN" --no-app-logs --platform="dotnet" --debug
        fi
  
    - name: Deploy Admin to Liara
      env:
        LIARA_API_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
      run: |
        if [ "${{ github.ref }}" == "refs/heads/master" ]; then
          liara deploy --app pro-admin-shemsh --port 80 --path ./deploy-src/admin/Gold.Admin.csproj --api-token="$LIARA_API_TOKEN" --platform="dotnet" --debug --no-app-logs
        fi
